#!/usr/bin/env python

# DESCRIPTION: Automatically fill the form of the site http://www.die-startseite.ch/Bern/ to send free sms to any swiss mobile numbers
# USAGE: sms <swiss number> <message>
# EXAMPLE: sms 0791234567 This is a message
# REMARK: requires python-mechanize: `pip install mechanize`

import re
import mechanize
import sys

browser=mechanize.Browser()
browser.open('http://www.die-startseite.ch/Bern/')
browser.select_form(name='smsBooster')
browser['intlPrefix'] = ['0041'+sys.argv[1][1:3]]
browser['SMSEingabe'] = sys.argv[1][3:]
browser.form.new_control('text','smsMessage',{'value':''})
browser.form.fixup()
browser.form['smsMessage'] = str(" ".join(sys.argv[2:]))
browser.submit()
